### ISSUE TITLE
Visual Studio Task Example Does not create the Temp file needed

### ISSUE THREAD

**Issue by ljg701** [em00k/NextBuild#1]
The Visual Studio Code example provided does not create the temp file needed. Compilation only works if there is an already existing temp file in the directory.

I've included a Task file here which creates the necessary temp file, and then calls compile.bat (The task to run is called Boriel Compile and Run)

[tasks.txt](https://github.com/em00k/NextBuild/files/4275419/tasks.txt)

**Comment by em00k** [comment]
Thanks!

**Comment by ljg701** [comment]
Can be closed, cheers.
