### ISSUE TITLE
Compilation failed - windows

### ISSUE THREAD

**Issue by JB1zzel** [em00k/NextBuild#20]
I can compile files. I just get the following error.

22:09:09 -> : Compilation failed
 22:09:12 ->                                                                                    
 22:09:12 -> Compilation time: 3547ms

**Comment by JB1zzel** [comment]
13:04:25 -> Compilation starts(440 Lines) 
 13:04:25 -> Source C:\Users\NextBuild-master\Sources\Sprites\MovingSprites.bas saved
 13:04:25 -> C:\Users\NextBuild-master\Scripts\Compile.bat "C:\Users\Jamie\Downloads\spectrum stuff\NextBuild-master\NextBuild-master\Sources\Sprites\temp.bas" -S 24576 -o "output.bin"  --heap-size=1000


 13:04:26 ->
Exit code: 1

'C:\Users\' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.

 13:04:26 -> : Compilation failed
 13:04:29 ->                                                                                    
 13:04:29 -> Compilation time: 3954ms

**Comment by em00k** [comment]
Please use VScode as instructed in the documentation. BorIDE will be removed from the release as it's no longer supported and was only included still if people needed to migrate code. Thanks.

**Comment by em00k** [comment]
closed
