### ISSUE TITLE
Make a new repository for NextLib

### ISSUE THREAD

**Issue by Duefectu** [em00k/NextBuild#6]
I love NextBuild. It's very fast programing start for ZX Next. Zero config is lovelly!

But with BorIDE abandoned, the next step is jump to VSCode or other editor.

An Boriel is working on v2 ZX Basic.

I think that is a good choice to detach NextLib from NextBuild.

**Comment by em00k** [comment]
For the time being I will leave it as it is, because until I know what ZXBasic v2 will look like its not worth splitting things up and I still want the package NextBuild to be a single download and run setup.
